#!/bin/bash
# Copyright 2022 ETH Zurich and University of Bologna.
# Solderpad Hardware License, Version 0.51, see LICENSE for details.
# SPDX-License-Identifier: SHL-0.51

# Thomas Benz <tbenz@iis.ee.ethz.ch>

set -e
ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)

EXCLUDED=" \
"

# Hardware files
echo "Hardware Files"
echo "----------------------------------------"
echo
python3 util/list-contributors.py ".sv .svh" "$EXCLUDED"
echo

# Scripts files
echo "Scripts Files"
echo "----------------------------------------"
echo
python3 util/list-contributors.py ".tcl .py .sh .do" "$EXCLUDED"
echo

# Config files
echo "Config Files"
echo "----------------------------------------"
echo
python3 util/list-contributors.py ".yml .hjson .json" "$EXCLUDED"
echo

# Code files
echo "Code Files"
echo "----------------------------------------"
echo
python3 util/list-contributors.py ".S .c .h" "$EXCLUDED"
echo

# Various files
echo "Various Files"
echo "----------------------------------------"
echo
python3 util/list-contributors.py "Makefile .verible .tpl .rst .gitignore .md" "$EXCLUDED"
