#!/usr/sepp/bin/vcs-2020.12 bash
# Copyright 2022 ETH Zurich and University of Bologna.
# Solderpad Hardware License, Version 0.51, see LICENSE for details.
# SPDX-License-Identifier: SHL-0.51

bin/axi_llc.vcs +vcs+lic+wait | tee logs/axi_llc.vcs.log
