// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package axi_llc_reg_pkg;

  // Address widths within the block
  parameter int BlockAw = 8;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {
    logic [31:0] q;
  } axi_llc_reg2hw_cfg_spm_low_reg_t;

  typedef struct packed {
    logic [31:0] q;
  } axi_llc_reg2hw_cfg_spm_high_reg_t;

  typedef struct packed {
    logic [31:0] q;
  } axi_llc_reg2hw_cfg_flush_low_reg_t;

  typedef struct packed {
    logic [31:0] q;
  } axi_llc_reg2hw_cfg_flush_high_reg_t;

  typedef struct packed {
    logic [31:0] q;
  } axi_llc_reg2hw_cfg_flush_set0_low_reg_t;

  typedef struct packed {
    logic [31:0] q;
  } axi_llc_reg2hw_cfg_flush_set0_high_reg_t;

  typedef struct packed {
    logic [31:0] q;
  } axi_llc_reg2hw_cfg_flush_set1_low_reg_t;

  typedef struct packed {
    logic [31:0] q;
  } axi_llc_reg2hw_cfg_flush_set1_high_reg_t;

  typedef struct packed {
    logic [31:0] q;
  } axi_llc_reg2hw_cfg_flush_set2_low_reg_t;

  typedef struct packed {
    logic [31:0] q;
  } axi_llc_reg2hw_cfg_flush_set2_high_reg_t;

  typedef struct packed {
    logic [31:0] q;
  } axi_llc_reg2hw_cfg_flush_set3_low_reg_t;

  typedef struct packed {
    logic [31:0] q;
  } axi_llc_reg2hw_cfg_flush_set3_high_reg_t;

  typedef struct packed {
    logic        q;
  } axi_llc_reg2hw_commit_cfg_reg_t;

  typedef struct packed {
    logic [31:0] q;
  } axi_llc_reg2hw_flushed_low_reg_t;

  typedef struct packed {
    logic [31:0] q;
  } axi_llc_reg2hw_flushed_high_reg_t;

  typedef struct packed {
    logic [31:0] q;
  } axi_llc_reg2hw_flushed_set0_low_reg_t;

  typedef struct packed {
    logic [31:0] q;
  } axi_llc_reg2hw_flushed_set0_high_reg_t;

  typedef struct packed {
    logic [31:0] q;
  } axi_llc_reg2hw_flushed_set1_low_reg_t;

  typedef struct packed {
    logic [31:0] q;
  } axi_llc_reg2hw_flushed_set1_high_reg_t;

  typedef struct packed {
    logic [31:0] q;
  } axi_llc_reg2hw_flushed_set2_low_reg_t;

  typedef struct packed {
    logic [31:0] q;
  } axi_llc_reg2hw_flushed_set2_high_reg_t;

  typedef struct packed {
    logic [31:0] q;
  } axi_llc_reg2hw_flushed_set3_low_reg_t;

  typedef struct packed {
    logic [31:0] q;
  } axi_llc_reg2hw_flushed_set3_high_reg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } axi_llc_hw2reg_cfg_spm_low_reg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } axi_llc_hw2reg_cfg_spm_high_reg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } axi_llc_hw2reg_cfg_flush_low_reg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } axi_llc_hw2reg_cfg_flush_high_reg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } axi_llc_hw2reg_cfg_flush_set0_low_reg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } axi_llc_hw2reg_cfg_flush_set0_high_reg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } axi_llc_hw2reg_cfg_flush_set1_low_reg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } axi_llc_hw2reg_cfg_flush_set1_high_reg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } axi_llc_hw2reg_cfg_flush_set2_low_reg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } axi_llc_hw2reg_cfg_flush_set2_high_reg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } axi_llc_hw2reg_cfg_flush_set3_low_reg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } axi_llc_hw2reg_cfg_flush_set3_high_reg_t;

  typedef struct packed {
    logic        d;
    logic        de;
  } axi_llc_hw2reg_commit_cfg_reg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } axi_llc_hw2reg_flushed_low_reg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } axi_llc_hw2reg_flushed_high_reg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } axi_llc_hw2reg_bist_out_low_reg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } axi_llc_hw2reg_bist_out_high_reg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } axi_llc_hw2reg_set_asso_low_reg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } axi_llc_hw2reg_set_asso_high_reg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } axi_llc_hw2reg_num_lines_low_reg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } axi_llc_hw2reg_num_lines_high_reg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } axi_llc_hw2reg_num_blocks_low_reg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } axi_llc_hw2reg_num_blocks_high_reg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } axi_llc_hw2reg_version_low_reg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } axi_llc_hw2reg_version_high_reg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } axi_llc_hw2reg_flushed_set0_low_reg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } axi_llc_hw2reg_flushed_set0_high_reg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } axi_llc_hw2reg_flushed_set1_low_reg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } axi_llc_hw2reg_flushed_set1_high_reg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } axi_llc_hw2reg_flushed_set2_low_reg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } axi_llc_hw2reg_flushed_set2_high_reg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } axi_llc_hw2reg_flushed_set3_low_reg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } axi_llc_hw2reg_flushed_set3_high_reg_t;

  // Register -> HW type
  typedef struct packed {
    axi_llc_reg2hw_cfg_spm_low_reg_t cfg_spm_low; // [704:673]
    axi_llc_reg2hw_cfg_spm_high_reg_t cfg_spm_high; // [672:641]
    axi_llc_reg2hw_cfg_flush_low_reg_t cfg_flush_low; // [640:609]
    axi_llc_reg2hw_cfg_flush_high_reg_t cfg_flush_high; // [608:577]
    axi_llc_reg2hw_cfg_flush_set0_low_reg_t cfg_flush_set0_low; // [576:545]
    axi_llc_reg2hw_cfg_flush_set0_high_reg_t cfg_flush_set0_high; // [544:513]
    axi_llc_reg2hw_cfg_flush_set1_low_reg_t cfg_flush_set1_low; // [512:481]
    axi_llc_reg2hw_cfg_flush_set1_high_reg_t cfg_flush_set1_high; // [480:449]
    axi_llc_reg2hw_cfg_flush_set2_low_reg_t cfg_flush_set2_low; // [448:417]
    axi_llc_reg2hw_cfg_flush_set2_high_reg_t cfg_flush_set2_high; // [416:385]
    axi_llc_reg2hw_cfg_flush_set3_low_reg_t cfg_flush_set3_low; // [384:353]
    axi_llc_reg2hw_cfg_flush_set3_high_reg_t cfg_flush_set3_high; // [352:321]
    axi_llc_reg2hw_commit_cfg_reg_t commit_cfg; // [320:320]
    axi_llc_reg2hw_flushed_low_reg_t flushed_low; // [319:288]
    axi_llc_reg2hw_flushed_high_reg_t flushed_high; // [287:256]
    axi_llc_reg2hw_flushed_set0_low_reg_t flushed_set0_low; // [255:224]
    axi_llc_reg2hw_flushed_set0_high_reg_t flushed_set0_high; // [223:192]
    axi_llc_reg2hw_flushed_set1_low_reg_t flushed_set1_low; // [191:160]
    axi_llc_reg2hw_flushed_set1_high_reg_t flushed_set1_high; // [159:128]
    axi_llc_reg2hw_flushed_set2_low_reg_t flushed_set2_low; // [127:96]
    axi_llc_reg2hw_flushed_set2_high_reg_t flushed_set2_high; // [95:64]
    axi_llc_reg2hw_flushed_set3_low_reg_t flushed_set3_low; // [63:32]
    axi_llc_reg2hw_flushed_set3_high_reg_t flushed_set3_high; // [31:0]
  } axi_llc_reg2hw_t;

  // HW -> register type
  typedef struct packed {
    axi_llc_hw2reg_cfg_spm_low_reg_t cfg_spm_low; // [1057:1025]
    axi_llc_hw2reg_cfg_spm_high_reg_t cfg_spm_high; // [1024:992]
    axi_llc_hw2reg_cfg_flush_low_reg_t cfg_flush_low; // [991:959]
    axi_llc_hw2reg_cfg_flush_high_reg_t cfg_flush_high; // [958:926]
    axi_llc_hw2reg_cfg_flush_set0_low_reg_t cfg_flush_set0_low; // [925:893]
    axi_llc_hw2reg_cfg_flush_set0_high_reg_t cfg_flush_set0_high; // [892:860]
    axi_llc_hw2reg_cfg_flush_set1_low_reg_t cfg_flush_set1_low; // [859:827]
    axi_llc_hw2reg_cfg_flush_set1_high_reg_t cfg_flush_set1_high; // [826:794]
    axi_llc_hw2reg_cfg_flush_set2_low_reg_t cfg_flush_set2_low; // [793:761]
    axi_llc_hw2reg_cfg_flush_set2_high_reg_t cfg_flush_set2_high; // [760:728]
    axi_llc_hw2reg_cfg_flush_set3_low_reg_t cfg_flush_set3_low; // [727:695]
    axi_llc_hw2reg_cfg_flush_set3_high_reg_t cfg_flush_set3_high; // [694:662]
    axi_llc_hw2reg_commit_cfg_reg_t commit_cfg; // [661:660]
    axi_llc_hw2reg_flushed_low_reg_t flushed_low; // [659:627]
    axi_llc_hw2reg_flushed_high_reg_t flushed_high; // [626:594]
    axi_llc_hw2reg_bist_out_low_reg_t bist_out_low; // [593:561]
    axi_llc_hw2reg_bist_out_high_reg_t bist_out_high; // [560:528]
    axi_llc_hw2reg_set_asso_low_reg_t set_asso_low; // [527:495]
    axi_llc_hw2reg_set_asso_high_reg_t set_asso_high; // [494:462]
    axi_llc_hw2reg_num_lines_low_reg_t num_lines_low; // [461:429]
    axi_llc_hw2reg_num_lines_high_reg_t num_lines_high; // [428:396]
    axi_llc_hw2reg_num_blocks_low_reg_t num_blocks_low; // [395:363]
    axi_llc_hw2reg_num_blocks_high_reg_t num_blocks_high; // [362:330]
    axi_llc_hw2reg_version_low_reg_t version_low; // [329:297]
    axi_llc_hw2reg_version_high_reg_t version_high; // [296:264]
    axi_llc_hw2reg_flushed_set0_low_reg_t flushed_set0_low; // [263:231]
    axi_llc_hw2reg_flushed_set0_high_reg_t flushed_set0_high; // [230:198]
    axi_llc_hw2reg_flushed_set1_low_reg_t flushed_set1_low; // [197:165]
    axi_llc_hw2reg_flushed_set1_high_reg_t flushed_set1_high; // [164:132]
    axi_llc_hw2reg_flushed_set2_low_reg_t flushed_set2_low; // [131:99]
    axi_llc_hw2reg_flushed_set2_high_reg_t flushed_set2_high; // [98:66]
    axi_llc_hw2reg_flushed_set3_low_reg_t flushed_set3_low; // [65:33]
    axi_llc_hw2reg_flushed_set3_high_reg_t flushed_set3_high; // [32:0]
  } axi_llc_hw2reg_t;

  // Register offsets
  parameter logic [BlockAw-1:0] AXI_LLC_CFG_SPM_LOW_OFFSET = 8'h 0;
  parameter logic [BlockAw-1:0] AXI_LLC_CFG_SPM_HIGH_OFFSET = 8'h 4;
  parameter logic [BlockAw-1:0] AXI_LLC_CFG_FLUSH_LOW_OFFSET = 8'h 8;
  parameter logic [BlockAw-1:0] AXI_LLC_CFG_FLUSH_HIGH_OFFSET = 8'h c;
  parameter logic [BlockAw-1:0] AXI_LLC_CFG_FLUSH_SET0_LOW_OFFSET = 8'h 10;
  parameter logic [BlockAw-1:0] AXI_LLC_CFG_FLUSH_SET0_HIGH_OFFSET = 8'h 14;
  parameter logic [BlockAw-1:0] AXI_LLC_CFG_FLUSH_SET1_LOW_OFFSET = 8'h 18;
  parameter logic [BlockAw-1:0] AXI_LLC_CFG_FLUSH_SET1_HIGH_OFFSET = 8'h 1c;
  parameter logic [BlockAw-1:0] AXI_LLC_CFG_FLUSH_SET2_LOW_OFFSET = 8'h 20;
  parameter logic [BlockAw-1:0] AXI_LLC_CFG_FLUSH_SET2_HIGH_OFFSET = 8'h 24;
  parameter logic [BlockAw-1:0] AXI_LLC_CFG_FLUSH_SET3_LOW_OFFSET = 8'h 28;
  parameter logic [BlockAw-1:0] AXI_LLC_CFG_FLUSH_SET3_HIGH_OFFSET = 8'h 2c;
  parameter logic [BlockAw-1:0] AXI_LLC_COMMIT_CFG_OFFSET = 8'h 30;
  parameter logic [BlockAw-1:0] AXI_LLC_FLUSHED_LOW_OFFSET = 8'h 38;
  parameter logic [BlockAw-1:0] AXI_LLC_FLUSHED_HIGH_OFFSET = 8'h 3c;
  parameter logic [BlockAw-1:0] AXI_LLC_BIST_OUT_LOW_OFFSET = 8'h 40;
  parameter logic [BlockAw-1:0] AXI_LLC_BIST_OUT_HIGH_OFFSET = 8'h 44;
  parameter logic [BlockAw-1:0] AXI_LLC_SET_ASSO_LOW_OFFSET = 8'h 48;
  parameter logic [BlockAw-1:0] AXI_LLC_SET_ASSO_HIGH_OFFSET = 8'h 4c;
  parameter logic [BlockAw-1:0] AXI_LLC_NUM_LINES_LOW_OFFSET = 8'h 50;
  parameter logic [BlockAw-1:0] AXI_LLC_NUM_LINES_HIGH_OFFSET = 8'h 54;
  parameter logic [BlockAw-1:0] AXI_LLC_NUM_BLOCKS_LOW_OFFSET = 8'h 58;
  parameter logic [BlockAw-1:0] AXI_LLC_NUM_BLOCKS_HIGH_OFFSET = 8'h 5c;
  parameter logic [BlockAw-1:0] AXI_LLC_VERSION_LOW_OFFSET = 8'h 60;
  parameter logic [BlockAw-1:0] AXI_LLC_VERSION_HIGH_OFFSET = 8'h 64;
  parameter logic [BlockAw-1:0] AXI_LLC_FLUSHED_SET0_LOW_OFFSET = 8'h 68;
  parameter logic [BlockAw-1:0] AXI_LLC_FLUSHED_SET0_HIGH_OFFSET = 8'h 6c;
  parameter logic [BlockAw-1:0] AXI_LLC_FLUSHED_SET1_LOW_OFFSET = 8'h 70;
  parameter logic [BlockAw-1:0] AXI_LLC_FLUSHED_SET1_HIGH_OFFSET = 8'h 74;
  parameter logic [BlockAw-1:0] AXI_LLC_FLUSHED_SET2_LOW_OFFSET = 8'h 78;
  parameter logic [BlockAw-1:0] AXI_LLC_FLUSHED_SET2_HIGH_OFFSET = 8'h 7c;
  parameter logic [BlockAw-1:0] AXI_LLC_FLUSHED_SET3_LOW_OFFSET = 8'h 80;
  parameter logic [BlockAw-1:0] AXI_LLC_FLUSHED_SET3_HIGH_OFFSET = 8'h 84;

  // Register index
  typedef enum int {
    AXI_LLC_CFG_SPM_LOW,
    AXI_LLC_CFG_SPM_HIGH,
    AXI_LLC_CFG_FLUSH_LOW,
    AXI_LLC_CFG_FLUSH_HIGH,
    AXI_LLC_CFG_FLUSH_SET0_LOW,
    AXI_LLC_CFG_FLUSH_SET0_HIGH,
    AXI_LLC_CFG_FLUSH_SET1_LOW,
    AXI_LLC_CFG_FLUSH_SET1_HIGH,
    AXI_LLC_CFG_FLUSH_SET2_LOW,
    AXI_LLC_CFG_FLUSH_SET2_HIGH,
    AXI_LLC_CFG_FLUSH_SET3_LOW,
    AXI_LLC_CFG_FLUSH_SET3_HIGH,
    AXI_LLC_COMMIT_CFG,
    AXI_LLC_FLUSHED_LOW,
    AXI_LLC_FLUSHED_HIGH,
    AXI_LLC_BIST_OUT_LOW,
    AXI_LLC_BIST_OUT_HIGH,
    AXI_LLC_SET_ASSO_LOW,
    AXI_LLC_SET_ASSO_HIGH,
    AXI_LLC_NUM_LINES_LOW,
    AXI_LLC_NUM_LINES_HIGH,
    AXI_LLC_NUM_BLOCKS_LOW,
    AXI_LLC_NUM_BLOCKS_HIGH,
    AXI_LLC_VERSION_LOW,
    AXI_LLC_VERSION_HIGH,
    AXI_LLC_FLUSHED_SET0_LOW,
    AXI_LLC_FLUSHED_SET0_HIGH,
    AXI_LLC_FLUSHED_SET1_LOW,
    AXI_LLC_FLUSHED_SET1_HIGH,
    AXI_LLC_FLUSHED_SET2_LOW,
    AXI_LLC_FLUSHED_SET2_HIGH,
    AXI_LLC_FLUSHED_SET3_LOW,
    AXI_LLC_FLUSHED_SET3_HIGH
  } axi_llc_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] AXI_LLC_PERMIT [33] = '{
    4'b 1111, // index[ 0] AXI_LLC_CFG_SPM_LOW
    4'b 1111, // index[ 1] AXI_LLC_CFG_SPM_HIGH
    4'b 1111, // index[ 2] AXI_LLC_CFG_FLUSH_LOW
    4'b 1111, // index[ 3] AXI_LLC_CFG_FLUSH_HIGH
    4'b 1111, // index[ 4] AXI_LLC_CFG_FLUSH_SET0_LOW
    4'b 1111, // index[ 5] AXI_LLC_CFG_FLUSH_SET0_HIGH
    4'b 1111, // index[ 6] AXI_LLC_CFG_FLUSH_SET1_LOW
    4'b 1111, // index[ 7] AXI_LLC_CFG_FLUSH_SET1_HIGH
    4'b 1111, // index[ 8] AXI_LLC_CFG_FLUSH_SET2_LOW
    4'b 1111, // index[ 9] AXI_LLC_CFG_FLUSH_SET2_HIGH
    4'b 1111, // index[10] AXI_LLC_CFG_FLUSH_SET3_LOW
    4'b 1111, // index[11] AXI_LLC_CFG_FLUSH_SET3_HIGH
    4'b 0001, // index[12] AXI_LLC_COMMIT_CFG
    4'b 1111, // index[13] AXI_LLC_FLUSHED_LOW
    4'b 1111, // index[14] AXI_LLC_FLUSHED_HIGH
    4'b 1111, // index[15] AXI_LLC_BIST_OUT_LOW
    4'b 1111, // index[16] AXI_LLC_BIST_OUT_HIGH
    4'b 1111, // index[17] AXI_LLC_SET_ASSO_LOW
    4'b 1111, // index[18] AXI_LLC_SET_ASSO_HIGH
    4'b 1111, // index[19] AXI_LLC_NUM_LINES_LOW
    4'b 1111, // index[20] AXI_LLC_NUM_LINES_HIGH
    4'b 1111, // index[21] AXI_LLC_NUM_BLOCKS_LOW
    4'b 1111, // index[22] AXI_LLC_NUM_BLOCKS_HIGH
    4'b 1111, // index[23] AXI_LLC_VERSION_LOW
    4'b 1111, // index[24] AXI_LLC_VERSION_HIGH
    4'b 1111, // index[25] AXI_LLC_FLUSHED_SET0_LOW
    4'b 1111, // index[26] AXI_LLC_FLUSHED_SET0_HIGH
    4'b 1111, // index[27] AXI_LLC_FLUSHED_SET1_LOW
    4'b 1111, // index[28] AXI_LLC_FLUSHED_SET1_HIGH
    4'b 1111, // index[29] AXI_LLC_FLUSHED_SET2_LOW
    4'b 1111, // index[30] AXI_LLC_FLUSHED_SET2_HIGH
    4'b 1111, // index[31] AXI_LLC_FLUSHED_SET3_LOW
    4'b 1111  // index[32] AXI_LLC_FLUSHED_SET3_HIGH
  };

endpackage

